USER_DATA = '../data/user'
USER_IMAGES = '../data/user/images'
USER_GRAPH = '../data/user/images/graph'
USER_HEATMAP = '../data/user/images/heatmap'
USER_COUNT_STATS = '../data/user/images/count_stats'
USER_STATS = '../data/user/mouse_stats'
USER_EVENT = '../data/user/mouse_event'
USER_IMG_AVG = '../data/user/images/avg_stats'

SUSPECT_DATA = '../data/suspect'
SUSPECT_IMAGES = '../data/suspect/{SUSPECT_NAME}/images'
SUSPECT_GRAPH = '../data/suspect/{SUSPECT_NAME}/images/graph'
SUSPECT_HEATMAP = '../data/suspect/{SUSPECT_NAME}/images/heatmap'
SUSPECT_COUNT_STATS = '../data/suspect/{SUSPECT_NAME}/images/count_stats'
SUSPECT_STATS = '../data/suspect/{SUSPECT_NAME}/mouse_stats'
SUSPECT_EVENT = '../data/suspect/{SUSPECT_NAME}/mouse_event'
SUSPECT_IMG_AVG = '../data/suspect/{SUSPECT_NAME}/images/avg_stats'
